spring:
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:datajpa/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        id:
          new_generator_mappings: true
        ejb:
          naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy



